Repository ShadyBoukhary/Axion-Technologies-HnH, pull requests merged in 2019-02, with the labels that each got.

#48 Added registration view, updated controller and presenter, and the re…
  lib/app/home/home_controller.dart
  lib/app/login/login_controller.dart
  lib/app/login/login_view.dart
  lib/app/main.dart
  lib/app/register/register_controller.dart
  lib/app/register/register_presenter.dart
  lib/app/register/register_view.dart
  lib/app/utils/consts.dart
  lib/data/repositories/data_authentication_repository.dart
  lib/domain/repositories/authentication_repository.dart
  lib/domain/usecases/auth/register_usecase.dart
  pubspec.yaml
Labels: Task

#55 Added countdown class for timer
  lib/app/components/countdown.dart
  lib/app/home/home_controller.dart
  lib/app/home/home_view.dart
Labels: Task, enhancement

#59 fixed checkbox error for Terms of Service
  lib/app/register/register_view.dart
Labels: Task, bug

#66 Create Event API: Routes, Controller, Model, and Interfaces
  backend/app/app.ts
  backend/app/controllers/eventController.ts
  backend/app/controllers/userController.ts
  backend/app/interfaces/event/event.ts
  backend/app/interfaces/event/eventDocument.ts
  backend/app/interfaces/event/eventModel.ts
  backend/app/interfaces/non_modals/coordinates.ts
  backend/app/interfaces/non_modals/location.ts
  backend/app/interfaces/userDocument.ts
  backend/app/models/eventModel.ts
  backend/app/models/userModel.ts
  backend/app/routes/eventRoute.ts
  backend/app/routes/userRoutes.ts
  lib/domain/entities/event.dart
  lib/domain/entities/event_registration.dart
  lib/domain/utils/utils.dart
  pubspec.yaml
  test/unit_tests/data_login_test.dart
  test/unit_tests/domain/event_registration_test.dart
  test/unit_tests/domain/event_test.dart
Labels: Domain, Server

#70 added page for maps, styling still required
  .gitignore
  android/app/src/main/AndroidManifest.xml
  lib/app/components/hhDrawer.dart
  lib/app/main.dart
  lib/app/map/map_controller.dart
  lib/app/map/map_presenter.dart
  lib/app/map/map_view.dart
  lib/app/splash/splash_presenter.dart
  pubspec.yaml
Labels: App, Task, enhancement

#71 added SRS_v1.0 documentation
  docs/HnH_SRS_V1.0.docx
Labels: Task
